# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='City')),
                ('latitude', models.CharField(max_length=200, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=200, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, verbose_name='Time')),
                ('temperature_max', models.CharField(max_length=200, verbose_name='Temperature max')),
                ('temperature_min', models.CharField(max_length=200, verbose_name='Temperature min')),
                ('temperature_day', models.CharField(max_length=200, verbose_name='Temperature day')),
                ('temperature_night', models.CharField(max_length=200, verbose_name='Temperature night')),
                ('wind', models.CharField(max_length=200, verbose_name='Wind')),
                ('cloudiness', models.CharField(max_length=200, verbose_name='Cloudiness')),
                ('pressure', models.CharField(max_length=200, verbose_name='Pressure')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.City')),
            ],
        ),
    ]
